gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#a9b665"
      - bold
    inactiveBorderColor:
      - "#45403d"
    optionsTextColor:
      - "#7daea3"
    selectedLineBgColor:
      - "#32302f"
    cherryPickedCommitBgColor:
      - "#32302f"
    cherryPickedCommitFgColor:
      - "#d3869b"
    unstagedChangesColor:
      - "#ea6962"
    defaultFgColor:
      - "#d4be98"
    searchingActiveBorderColor:
      - "#d8a657"
